# Exercise 3

Comparing the performance of XGB with a simple FFNN varying the size of validation set

In [6]:
from sklearn.model_selection import train_test_split
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

tf.random.set_seed(12345)

X = np.loadtxt("DATA/x_XGB_26.dat", delimiter=" ",dtype=float)
y = np.loadtxt("DATA/y_XGB_26.dat", delimiter=" ",dtype=float)

print(X)

val_fraction = [0.1, 0.2, 0.3, 0.4, 0.5]
for val in val_fraction:
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=val, random_state=42)
    print(f"Validation fraction: {val}, Training set size: {len(X_train)}")

    # Clean and define the FFNN model
    tf.keras.backend.clear_session()
    
    model = Sequential([
    Dense(128, activation='relu', input_shape=(4,)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),  
    Dense(1, activation='sigmoid') 
    ])

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_val, y_val), verbose=0)
    val_loss, val_acc = model.evaluate(X_val, y_val, verbose=0)
    print(f"Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_acc:.4f}\n")

[[-31.608 -29.544   6.773   9.554]
 [ 46.451  15.318  24.891  15.357]
 [ 24.771  46.131 -49.161 -39.356]
 ...
 [-32.939   8.801 -28.16  -10.964]
 [-22.286  47.154  40.197  32.428]
 [-46.287 -27.454 -47.655  48.126]]
Validation fraction: 0.1, Training set size: 4500
Validation Loss: 0.6792, Validation Accuracy: 0.5920

Validation fraction: 0.2, Training set size: 4000
Validation Loss: 0.6896, Validation Accuracy: 0.5730

Validation fraction: 0.3, Training set size: 3500


KeyboardInterrupt: 